%YAML 1.2
---
# https://docs.docker.com/reference/dockerfile
# http://www.sublimetext.com/docs/syntax.html
name: Containerfile
scope: source.containerfile
version: 2

extends: Packages/ShellScript/Bash.sublime-syntax

file_extensions:
  - Dockerfile
  - Containerfile

first_line_match: (?i)^from[ ][^:]+:[^:]+

variables:
  powershell_images: (?:microsoft|powershell|windows)

contexts:
  main:
    - include: docker-directives
    - include: docker-instructions
    - include: statements

  line-continuation-body:
    - meta_prepend: true
    - include: comments

####[ DOCKER DIRECTIVES ]######################################################

  docker-directives:
    - match: (\#)\s*(escape)(\s*(=)\s*(`))
      captures:
        1: punctuation.definition.comment.shell
        2: meta.annotation.identifier.containerfile variable.language.containerfile
        3: meta.annotation.containerfile
        4: keyword.operator.assignment.containerfile
      set:
        - scope:source.containerfile.powershell
        - docker-directive-body
    - match: (\#)\s*(\w+)(\s*(=)\s*)
      captures:
        1: punctuation.definition.comment.shell
        2: meta.annotation.identifier.containerfile variable.language.containerfile
        3: meta.annotation.containerfile
        4: keyword.operator.assignment.containerfile
      push: docker-directive-body

  docker-directive-body:
    - meta_scope: comment.line.number-sign.shell
    - meta_content_scope: meta.annotation.value.containerfile string.unquoted.shell
    - match: \n
      pop: 1

####[ DOCKER INSTRUCTIONS ]####################################################

  docker-instructions:
    # ARG
    - match: (?i:ARG){{cmd_break}}
      scope: keyword.declaration.arg.containerfile
      push: cmd-arg-args
    # COPY
    - match: (?i:COPY){{cmd_break}}
      scope: keyword.other.containerfile
      push: cmd-copy-args
    # ENV
    - match: (?i:ENV){{cmd_break}}
      scope: keyword.declaration.env.containerfile
      push: cmd-env-args
    # FROM
    - match: (?i:FROM)(?=\s+\S*{{powershell_images}})
      scope: keyword.control.import.from.containerfile
      set:
        - scope:source.containerfile.powershell
        - cmd-from-args
    - match: (?i:FROM){{cmd_break}}
      scope: keyword.control.import.from.containerfile
      push: cmd-from-args
    # LABEL
    - match: (?i:LABEL){{cmd_break}}
      scope: keyword.declaration.label.containerfile
      push: cmd-label-args
    # ONBUILD
    - match: (?i:ONBUILD){{cmd_break}}
      scope: keyword.other.containerfile
    # RUN
    - match: (?i:CMD|ENTRYPOINT|HEALTHCHECK|RUN|SHELL){{cmd_break}}
      scope: keyword.control.flow.containerfile
      push: cmd-run-args
    # other
    - match: (?i:ADD|EXPOSE|STOPSIGNAL|USER|VOLUME|WORKDIR){{cmd_break}}
      scope: keyword.other.containerfile
      push: cmd-args

####[ ARG INSTRUCTIONS ]#######################################################

  cmd-arg-args:
    - meta_include_prototype: false
    - include: cmd-args-end
    - match: '{{variable_begin}}'
      push:
        - literal-array-value-assignment
        - arg-name-chars
    - include: illegal-words

  arg-name-chars:
    - meta_content_scope: variable.parameter.containerfile
    - match: (?=[=\s])
      pop: 1
    - include: literal-unquoted-content

####[ COPY INSTRUCTIONS ]######################################################

  cmd-copy-args:
    - meta_include_prototype: false
    - meta_content_scope: meta.function-call.arguments.shell
    # content as heredoc
    - match: (<<-)\s*(?=["'\\]?({{heredoc}}))
      captures:
        1: keyword.operator.assignment.redirection.containerfile
      embed: cmd-copy-heredoc-begin
      escape: '{{tab_indent}}(\2)$\n?'
      escape_captures:
        0: meta.redirection.containerfile meta.tag.heredoc.end.containerfile
        1: entity.name.tag.heredoc.containerfile
      pop: 1
    - match: (<<)\s*(?=["'\\]?({{heredoc}}))
      captures:
        1: keyword.operator.assignment.redirection.containerfile
      embed: cmd-copy-heredoc-begin
      escape: '{{no_indent}}(\2)$\n?'
      escape_captures:
        0: meta.redirection.containerfile meta.tag.heredoc.end.containerfile
        1: entity.name.tag.heredoc.containerfile
      pop: 1
    - include: cmd-args

  cmd-copy-heredoc-begin:
    # Same as Bash HEREDOC, but with variable expansion in all variants
    - meta_include_prototype: false
    - meta_scope: meta.redirection.containerfile
    - match: (')({{heredoc}})(')
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.begin.containerfile
        2: entity.name.tag.heredoc.containerfile
        3: punctuation.definition.tag.end.containerfile
      push:
        - heredoc-preamble
        - cmd-args
    - match: (")({{heredoc}})(")
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.begin.containerfile
        2: entity.name.tag.heredoc.containerfile
        3: punctuation.definition.tag.end.containerfile
      push:
        - heredoc-preamble
        - cmd-args
    - match: (\\)({{heredoc}})
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.containerfile
        2: entity.name.tag.heredoc.containerfile
      push:
        - heredoc-preamble
        - cmd-args
    - match: '{{heredoc}}'
      scope: meta.tag.heredoc.begin.containerfile entity.name.tag.heredoc.containerfile
      push:
        - heredoc-preamble
        - cmd-args

####[ ENV INSTRUCTIONS ]#######################################################

  cmd-env-args:
    - match: (\w+)\b\s*(?!=)
      captures:
        1: meta.assignment.l-value.shell variable.other.readwrite.shell
      set: literal-array-value
    - include: cmd-export-args

####[ FROM INSTRUCTIONS ]######################################################

  cmd-from-args:
    - meta_include_prototype: false
    - meta_scope: meta.import.containerfile
    - include: cmd-args-options
    - match: (?=\S)
      push:
        - from-container-alias
        - from-container-name-chars
    - match: $
      pop: 1

  from-container-name-chars:
    - meta_content_scope: meta.namespace.containerfile support.module.containerfile
    - match: '@'
      scope: meta.namespace.containerfile punctuation.separator.key-value.containerfile
      set: from-container-hash-chars
    - match: ':'
      scope: meta.namespace.containerfile punctuation.separator.key-value.containerfile
      set: from-container-tag-chars
    - match: (?=\s)
      pop: 1
    - include: literal-unquoted-content

  from-container-tag-chars:
    - meta_content_scope: meta.namespace.containerfile constant.language.ref.tag.containerfile
    - match: (?=\s)
      pop: 1
    - include: literal-unquoted-content

  from-container-hash-chars:
    - meta_content_scope: meta.namespace.containerfile constant.language.ref.digest.containerfile
    - match: (?=\s)
      pop: 1
    - include: literal-unquoted-content

  from-container-alias:
    - match: ((?i:as))\s+([-\w]+)
      captures:
        1: keyword.operator.assignment.as.containerfile
        2: entity.name.label.containerfile
      pop: 2
    - match: $
      pop: 2

####[ LABEL INSTRUCTION ]######################################################

  cmd-label-args:
    - meta_include_prototype: false
    - include: cmd-args-end
    - match: '{{variable_begin}}'
      push:
        - literal-array-value-assignment
        - label-name-chars
    - include: illegal-words

  label-name-chars:
    - meta_content_scope: variable.label.containerfile
    - match: (?=[=\s])
      pop: 1
    - include: literal-unquoted-content

####[ RUN INSTRUCTIONS ]#######################################################

  cmd-run-args:
    - meta_include_prototype: false
    - meta_content_scope: meta.function-call.arguments.shell
    # command line as list of strings
    - match: \[
      scope: punctuation.section.sequence.begin.containerfile
      set:
        - cmd-run-argument-list-body
        - cmd-run-command-name
    # script as heredoc
    - match: (<<-)\s*(?=["'\\]?({{heredoc}}))
      captures:
        1: keyword.operator.assignment.redirection.containerfile
      embed: cmd-run-heredoc-begin
      escape: '{{tab_indent}}(\2)$\n?'
      escape_captures:
        0: meta.redirection.containerfile meta.tag.heredoc.end.containerfile
        1: entity.name.tag.heredoc.containerfile
      pop: 1
    - match: (<<)\s*(?=["'\\]?({{heredoc}}))
      captures:
        1: keyword.operator.assignment.redirection.containerfile
      embed: cmd-run-heredoc-begin
      escape: '{{no_indent}}(\2)$\n?'
      escape_captures:
        0: meta.redirection.containerfile meta.tag.heredoc.end.containerfile
        1: entity.name.tag.heredoc.containerfile
      pop: 1
    # command line in shell form
    - include: cmd-exec-args

  cmd-run-command-name:
    - match: \"
      scope: punctuation.definition.quoted.begin.shell
      set:
        - cmd-run-command-name-body
        - path-pattern-quoted-begin
    - include: comments
    - include: else-pop

  cmd-run-command-name-body:
    - meta_scope: meta.function-call.identifier.shell meta.command.shell variable.function.shell
    - include: path-pattern-double-quoted-body

  cmd-run-argument-list-body:
    - meta_include_prototype: false
    - meta_scope: meta.function-call.arguments.shell meta.sequence.list.containerfile
    - match: \]
      scope: punctuation.section.sequence.end.containerfile
      pop: 1
    - match: \"
      scope: punctuation.definition.string.begin.shell
      push: cmd-run-arg-body
    - include: comma-separators
    - include: comments

  cmd-run-arg-body:
    - meta_scope: meta.string.glob.shell string.quoted.double.shell
    - include: string-path-pattern-double-quoted-body

  cmd-run-heredoc-begin:
    # Same as Bash HEREDOC, but with Bash highlighting in all variants
    - meta_include_prototype: false
    - meta_scope: meta.redirection.containerfile
    - match: (')({{heredoc}})(')
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.begin.containerfile
        2: entity.name.tag.heredoc.containerfile
        3: punctuation.definition.tag.end.containerfile
      push:
        - cmd-run-heredoc-body
        - cmd-args
    - match: (")({{heredoc}})(")
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.begin.containerfile
        2: entity.name.tag.heredoc.containerfile
        3: punctuation.definition.tag.end.containerfile
      push:
        - cmd-run-heredoc-body
        - cmd-args
    - match: (\\)({{heredoc}})
      scope: meta.tag.heredoc.begin.containerfile
      captures:
        1: punctuation.definition.tag.containerfile
        2: entity.name.tag.heredoc.containerfile
      push:
        - cmd-run-heredoc-body
        - cmd-args
    - match: '{{heredoc}}'
      scope: meta.tag.heredoc.begin.containerfile entity.name.tag.heredoc.containerfile
      push:
        - cmd-run-heredoc-body
        - cmd-args

  cmd-run-heredoc-body:
    - include: statements
